import { config, library } from "@fortawesome/fontawesome-svg-core";
import {
  faMagnifyingGlass,
  faUser,
  faHeart,
  faBagShopping,
  faBars,
  faXmark,
  faStar,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faArrowRight,
  faArrowDown,
  faCheck,
  faImage,
  faEnvelope,
  faGift,
  faGear,
  faClipboardList,
  faLayerGroup,
  faCubes,
  faBookOpen,
  faPrint,
  faPaintbrush,
  faSun,
} from "@fortawesome/free-solid-svg-icons";
import { faInstagram, faTiktok } from "@fortawesome/free-brands-svg-icons";
import { faHeart as faHeartRegular } from "@fortawesome/free-regular-svg-icons";

config.autoAddCss = false;

library.add(
  faMagnifyingGlass,
  faUser,
  faHeart,
  faBagShopping,
  faBars,
  faXmark,
  faStar,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faArrowRight,
  faArrowDown,
  faCheck,
  faImage,
  faEnvelope,
  faGift,
  faGear,
  faClipboardList,
  faLayerGroup,
  faCubes,
  faBookOpen,
  faPrint,
  faPaintbrush,
  faSun,
  faInstagram,
  faTiktok,
  faHeartRegular,
);
